name: Build and Release
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # 1. Проверка репозитория
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Настройка Gradle
      - uses: gradle/actions/setup-gradle@v3

      # 3. Настройка Java
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
          cache: 'gradle'

      # 4. Делает gradlew исполняемым
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      # 5. Получаем версию мода
      - name: Get mod version
        id: get_version
        run: |
          MOD_VERSION=$(grep "^mod.version=" gradle.properties | cut -d'=' -f2)
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV

      # 6. Билд всех версий
      - name: Build all versions
        run: ./gradlew shadowJar --stacktrace --info

      # 7. Загружаем артефакты для проверки
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CIM-builds
          path: versions/*/build/libs/*.jar

      # 8. Создаем или обновляем релиз с тегом по версии мода
      - name: Create or Update Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.MC_MOD_CUSTOMITEMMODEL_ACTION }}
          automatic_release_tag: "v${{ env.MOD_VERSION }}"
          release_name: "Release v${{ env.MOD_VERSION }}"
          prerelease: false
          files: versions/*/build/libs/*.jar
