name: build
on:
  push:
    branches: [ main, dev, feature/** ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        mc_version: [ "1.21.1" ]
        loader: [ "fabric" ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: gradle/actions/setup-gradle@v3

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
          cache: 'gradle'

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      # Определяем ветку для приставки
      - name: Set branch suffix
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          echo "branchSuffix=$BRANCH_NAME" >> $GITHUB_ENV

      # Билд
      - name: Build ${{ matrix.loader }} for MC ${{ matrix.mc_version }}
        run: ./gradlew shadowJar \
              -PmcVersion=${{ matrix.mc_version }} \
              -Ploader=${{ matrix.loader }} \
              -PbranchSuffix=${{ env.branchSuffix }} \
              --stacktrace --info

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CIM-${{ matrix.mc_version }}-${{ matrix.loader }}-${{ env.branchSuffix }}
          path: build/libs/*.jar
