name: build
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        mc_version: [ "1.21.1" ]
        loader: [ "fabric" ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: gradle/actions/setup-gradle@v3

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
          cache: 'gradle'

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      # Получаем версию из gradle.properties
      - name: Get mod version
        id: get_version
        run: |
          VERSION=$(grep mod_version gradle.properties | cut -d'=' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Билд
      - name: Build ${{ matrix.loader }} for MC ${{ matrix.mc_version }}
        run: ./gradlew shadowJar -PmcVersion=${{ matrix.mc_version }} -Ploader=${{ matrix.loader }} --stacktrace --info

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CIM-${{ env.VERSION }}-${{ matrix.loader }}
          path: build/libs/*.jar

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.VERSION }}-release
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.MC_MOD_CUSTOMITEMMODEL_ACTION }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/CIM-${{ env.VERSION }}-${{ matrix.loader }}.jar
          asset_name: CIM-${{ env.VERSION }}${{ matrix.loader }}.jar
          asset_content_type: application/java-archive
