name: Build and Release
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # === Checkout repo ===
      - name: Checkout repository
        uses: actions/checkout@v4

      # === Gradle setup ===
      - uses: gradle/actions/setup-gradle@v3

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
          cache: 'gradle'

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      # === Get mod version ===
      - name: Get mod version
        id: get_version
        run: |
          MOD_VERSION=$(grep "^mod.version=" gradle.properties | cut -d'=' -f2)
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV

      # === Build all versions ===
      - name: Build all versions
        run: ./gradlew shadowJar --stacktrace --info

      # === Upload artifacts for debugging ===
      - name: Upload all jar artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CIM-builds
          path: versions/*/build/libs/*.jar

      # === Create GitHub release ===
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}-release
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.MC_MOD_CUSTOMITEMMODEL_ACTION }}

      # === Upload all jars to release ===
      - name: Upload release assets
        run: |
          for jar in versions/*/build/libs/*.jar; do
            BASENAME=$(basename "$jar")
            echo "Uploading $BASENAME..."
            curl -s -X POST \
              -H "Authorization: token ${{ secrets.MC_MOD_CUSTOMITEMMODEL_ACTION }}" \
              -H "Content-Type: application/java-archive" \
              --data-binary @"$jar" \
              "${{ steps.create_release.outputs.upload_url }}?name=$BASENAME"
          done
