name: Build and Release

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.gen_matrix.outputs.matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Получаем mod.version и строим matrix
      - name: Generate matrix from gradle.properties
        id: gen_matrix
        run: |
          # мод версия
          version=$(grep "^mod.version=" gradle.properties | cut -d'=' -f2)
          echo "mod_version=$version" >> $GITHUB_ENV
          echo "Mod version: $version"

          # версии майна и лоадеры
          versions=$(grep "^workflow.versions=" gradle.properties | cut -d'=' -f2)
          loaders=$(grep "^workflow.loaders=" gradle.properties | cut -d'=' -f2)

          IFS=',' read -ra ver_list <<< "$versions"
          IFS=',' read -ra load_list <<< "$loaders"

          json="["
          for v in "${ver_list[@]}"; do
            for l in "${load_list[@]}"; do
              json="$json{\"mc\":\"$v\",\"loader\":\"$l\"},"
            done
          done
          json="${json::-1}]"
          echo "matrix=$json" >> $GITHUB_OUTPUT

  build_matrix:
    needs: build
    runs-on: ubuntu-22.04
    strategy:
      matrix: ${{fromJSON(needs.build.outputs.matrix)}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: gradle/actions/setup-gradle@v3

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
          cache: 'gradle'

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build ${{ matrix.loader }} for MC ${{ matrix.mc }}
        run: ./gradlew :versions:${{ matrix.mc }}-${{ matrix.loader }}:shadowJar --stacktrace --info

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CIM-${{ matrix.mc }}-${{ matrix.loader }}-${{ env.mod_version }}
          path: versions/${{ matrix.mc }}-${{ matrix.loader }}/build/libs/*.jar

  release:
    needs: build_matrix
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get mod version
        id: get_version
        run: |
          version=$(grep "^mod.version=" gradle.properties | cut -d'=' -f2)
          echo "mod_version=$version" >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: build-artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.mod_version }}-release
          release_name: Release ${{ env.mod_version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.MC_MOD_CUSTOMITEMMODEL_ACTION }}

      - name: Upload all artifacts to Release
        run: |
          for file in $(find build-artifacts -type f -name '*.jar'); do
            echo "Uploading $file"
            gh release upload "${{ env.mod_version }}-release" "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.MC_MOD_CUSTOMITEMMODEL_ACTION }}
